#######
# PSEUDO MAKEFILE
# this is a pseudo MAKEFILE for recording the workflow for
# downloading data from esgf. The focus here is on downloading
# monthly CH4 data from the input4MIPs project
#######

# create environment
uv venv --python 3.11

# activate environment
.venv/Scripts/activate

# install esgpull
uv pip install git+https://github.com/ESGF/esgf-download
uv run esgpull self install

# configure esgpull
uv run esgpull config api.index_node esgf-node.llnl.gov

# search for data set from input4MIPs project, monthly co2 data
esgpull search project:input4MIPs variable_id:ch4 frequency:mon grid_label:gm
# output:
# Found 2 datasets.
#  id │                                dataset                                │ # │  size
# ════╪═══════════════════════════════════════════════════════════════════════╪═══╪═════════
#   0 │ input4MIPs.CMIP7.CMIP.CR.CR-CMIP-1-0-0.atmos.mon.ch4.gm.v20250228     │ 3 │ 1.8 MiB
#   1 │ input4MIPs.CMIP6Plus.CMIP.CR.CR-CMIP-0-4-0.atmos.mon.ch4.gm.v20241205 │ 3 │ 1.8 MiB

# add data to query list
esgpull add project:input4MIPs variable_id:ch4 frequency:mon grid_label:gm --track
# output:
# <4dc7e3>
# └── distrib:     False
#     latest:      True
#     replica:     None
#     retracted:   False
#     frequency:   mon
#     grid_label:  gm
#     project:     input4MIPs
#     variable_id: ch4
# New query added: <4dc7e3>
# 👍 1 new query added.

# update queries
esgpull update 4dc7e3 -y
# output:
# Updating <4dc7e3> with 7 new files (5.5 MiB).
# Send to download queue? [y/n/show]: y
# <4dc7e3> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00

# download data in cue
esgpull download 4dc7e3
# output:
# <4dc7e3>
# └── distrib:     False
#     latest:      True
#     replica:     None
#     retracted:   False
#     frequency:   mon
#     grid_label:  gm
#     project:     input4MIPs
#     variable_id: ch4
#     files:       0 bytes / 5.5 MiB [0/7]
# <9d98ca> · 264.2 kiB · 169.0 kiB/s · esgf-data2.llnl.gov
# <315a58> · 901.2 kiB · 447.3 kiB/s · esgf-data2.llnl.gov
# <a0b8bd> · 266.8 kiB · 589.0 kiB/s · esgf-data2.llnl.gov
# <7545a1> · 679.9 kiB · 313.0 kiB/s · esgf-data2.llnl.gov
# <596243> · 903.9 kiB · 410.3 kiB/s · esgf-data2.llnl.gov
# <b153ab> · 682.6 kiB · 1.6 MiB/s · esgf-data2.llnl.gov
# <9973fb> · 1.8 MiB · 688.2 kiB/s · esgf-data2.llnl.gov
#   7/7 00:02
# Downloaded 7 new files for a total size of 5.5 MiB
